config/routes.rb
Rails.application.routes.draw do
  
  
  get 'teste/index'

  get 'teste/show'

  get 'tags/create'

  get 'tinymce_assets/create'

  resources :posts

  resources :categories

  resources :tags

  match 'home', controller: 'home', action: 'index', via: 'get'

  get 'home/index'

  devise_for :users
  root 'posts#index'

  post '/tinymce_assets' => 'tinymce_assets#create'


end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :posts, dependent: :destroy

	validates_presence_of :description
	validates_length_of :description, minimum: 2, maximum: 35
end

app/models/image.rb
class Image < ActiveRecord::Base
	has_attached_file :file
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  has_many :tags, dependent: :destroy
  
  accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank

  has_and_belongs_to_many :categories, dependent: :destroy

  validates_presence_of :title, :slug, :post_text
  validates_length_of :title, minimum: 2, maximum: 35
  validates_length_of :slug, minimum: 2, maximum: 35
  validates_length_of :post_text, minimum: 10


  scope :most_popular, where('clicks >= 10')
  scope :latest, order(:created_at).take(5)

  extend FriendlyId

  friendly_id :title, use: :slugged


  private

    def should_generate_new_friendly_id?
      new_record?
    end



end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post

  validates_presence_of :tag
  validates_length_of :tag, minimum: 2, maximum: 30
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  validates_presence_of :email, :encrypted_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	home_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  respond_to :html, :js, :json, :xml

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  respond_to :html, :js, :json, :xml

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
    respond_with(@posts)
  end

  def show
    @post.clicks += 1
    @post.save!
    respond_with(@post)
  end

  def new
    @categories = Category.order :description
    @post = Post.new
    @post.tags.build 
    respond_with(@post)
  end

  def edit
    @categories =  Category.order :description
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :slug, :post_text, :user_id, {category_ids: []}, tags_attributes: [:tag])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
  	@tag = Tag.find params[:id]
  	@posts = Tag.where(tag: @tag.tag).includes(:post)
  end
end

app/controllers/tinymce_assets_controller.rb
class TinymceAssetsController < ApplicationController
  before_filter :authenticate_user!
  
  respond_to :json

  def create
    geometry = Paperclip::Geometry.from_file params[:file]
    image    = Image.create params.permit(:file, :alt, :hint)

    render json: {
         image: {
             url:    image.file.url,
             height: geometry.height.to_i,
             width:  geometry.width.to_i
         }
     }, layout: false, content_type: "text/html"

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tinymce_assets_helper.rb
module TinymceAssetsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-sm-4">
        <%= f.label t(:category_name) %><br>
        <%= f.text_field :description, class: "form-control", required: true, maxlength: 35 %>
      </div>
  </div>
  <br />
  <div class="actions">
    <%= link_to t(:categories), categories_path, class: "btn btn-danger" %>
    <button type="submit" class="btn btn-primary"> <%=t(:save)%> </button>
  </div>
<% end %>

app/views/categories/_list.html.erb
<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>
      <%= t('description') %>
    </th>
    <th>

    </th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td class="col-sm-9"><%= category.description %></td>
        <td>
          <div style="text-align: center;">
            <div class="btn-group" style="" role="group" aria-label="...">
              <%= link_to t(:Posts), category, class: "btn btn-primary" %>
              <%= link_to t(:Edit), edit_category_path(category), class: "btn btn-success" if user_signed_in? %>
              <%= link_to t(:Destroy), category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" if user_signed_in? %>
            </div>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/categories/_list_posts.html.erb
<table class="table table-bordered">
	<thead>
		<th> <%= t(:title) %> </th>
		<th> <%= t(:user) %> </th>
		<th> <%= t(:published_at) %> </th>
		<th></th>
	</thead>
	<tbody>
		<% @category.posts.each do |post| %>
		<tr>
			<td> <%=post.title%> </td>
			<td> <%=post.user.email%> </td>
			<td> <%= l(post.created_at) %></td>
			<td> <%= link_to t(:see), post %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/categories/edit.html.erb
<legend><%= t(:edit_category) %></legend>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1><%= t('category.categories') %></h1>

<% if @categories.present? %>
    <%= render 'list' %>
<% else %>
    <div class="alert alert-info">
      <%=t('no_category_found')%>
    </div>
<% end %>

<div class="row">
  <div class="col-sm-10">
    <%= will_paginate @categories if @categories.present? %>
  </div>
  <div class="col-sm-2">
    <%= link_to 'New Category', new_category_path, class: "btn btn-info" if user_signed_in? %>
  </div>
</div>

app/views/categories/new.html.erb
<legend>New category</legend>

<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.description %>
</p>



<% if @category.posts.present? %>

	<%= render 'list_posts' %>

<% else %>

    <div class="alert alert-info">No post found for this category</div>

<% end %>


<%= link_to "Back", categories_path, class: "btn btn-danger" %>

app/views/home/index.html.erb
<div class="well">
<h1><%= t('hello') %>! <%= current_user.email %></h1> 

<p>
	<%= t('last_login') %> <%= l(current_user.last_sign_in_at) %>
</p>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Challenge" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'shared/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'shared/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-1">
        <%= f.label "Título:" %>
    </div>
    <div class="col-sm-4">
        <%= f.text_field :title, class: "form-control", maxlength: 50, required: true %>
    </div>
  </div>
  <hr>

  <div class="row">

    <div class="col-sm-4">
    
        <select id="post[category_ids][]" multiple="multiple" name="post[category_ids][]" class="form-control" size="10" required> 
          <% @categories.each do |category| %>
            <option value="<%= category.id %>"><%= category.description %></option>
          <% end %>  
        </select>
    </div>

  </div>

  <hr>

  <div class="row">
    <div class="col-sm-12">
      <%= f.fields_for :tags do |builder| %> 
        <%= render 'tags_field', f: builder %>
      <% end %>
    </div>
  </div>

  <hr>
  
  <div class="row">

    <div class="col-sm-12">
      <%= f.label :post_text %><br>
      <%= f.text_area :post_text, class: "tinymce", rows: 20 %>
      <%= tinymce %>
    </div>

  </div>


  <%= f.hidden_field :user_id, value: current_user.id %>

  <br />

  <div class="actions">
    <%= f.submit "Save post", class: "btn btn-success" %>
  </div>


<% end %>

app/views/posts/_list.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th><%=t('Title')%></th>
    <th><%=t('published_by')%></th>
    <th><%=t('published_on')%></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td class="col-sm-3"><%= post.user.email %> </td>
        <td class="col-sm-2"><%= post.created_at %></td>
        <td class="col-sm-3">
          <center>
            <%= link_to t('Show'), post, class: "btn btn-default" %>
            <%= link_to t('Edit'), edit_post_path(post), class: "btn btn-primary" if user_signed_in? %>
            <%= link_to t('Destroy'), post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" if user_signed_in? %>
          </center>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/_tag_fields.html.erb
<p>
  <label id="lbl-<%=f.__id__%>"> Tag: </label><br />
  <%= f.text_field :tag, id: "tag-#{f.__id__}" %> 
  <%= link_to_remove_association "remove", f %>
</p>

app/views/posts/edit.html.erb
<legend>Edit post</legend>

<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-1">
        <%= f.label "Título:" %>
    </div>
    <div class="col-sm-4">
        <%= f.text_field :title, class: "form-control", maxlength: 50, required: true %>
    </div>
  </div>
  <hr>

  <div class="row">

    <div class="col-sm-4">
    
        <select id="post[category_ids][]" multiple="multiple" name="post[category_ids][]" class="form-control" size="10" required> 
          <% @categories.each do |category| %>

            <% present = false %>

            <% @post.categories.each do |post_category| %>
            	<% present = true if category.id == post_category.id%>
            <% end %>

            <% if present %>
            	<option selected value="<%= category.id %>"><%= category.description %></option>
            <% else %>
            	<option value="<%= category.id %>"><%= category.description %></option>
            <% end %>

          <% end %>  
        </select>
    </div>

  </div>

  <hr>

  
  <div class="row">
    <div class="col-sm-12">
      <%= f.simple_fields_for :tags do |builder| %> 
        <%= render 'tag_fields', f: builder %>
      <% end %>
      <%= link_to_add_association 'add item', f, :tags, :class => "btn btn-default" %>
    </div>
  </div>

  <hr>
  
  <div class="row">

    <div class="col-sm-12">
      <%= f.label :post_text %><br>
      <%= f.text_area :post_text, class: "tinymce", rows: 20 %>
      <%= tinymce %>
    </div>

  </div>


  <%= f.hidden_field :user_id, value: current_user.id %>

  <br />

  <div class="actions">
    <%= f.submit "Save post", class: "btn btn-success" %>
  </div>


<% end %>

app/views/posts/index.html.erb
<legend> Posts </legend>


<% if @posts.present? %>
    <%= render 'list' %>
<% else %>
    <div class="alert alert-info">
      No posts found
    </div>
<% end %>

<br>

<div class="row">
  <div class="col-sm-10">
    <%= will_paginate @posts if @posts.present? %>
  </div>
  <div class="col-sm-2">
    <%= link_to 'New post', new_post_path, class: "btn btn-info" if user_signed_in?%>
  </div>
</div>

app/views/posts/new.html.erb
<legend> New post </legend>

<%= simple_form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-1">
        <%= f.label "Título:" %>
    </div>
    <div class="col-sm-4">
        <%= f.text_field :title, class: "form-control", maxlength: 50, required: true %>
    </div>
  </div>
  <hr>

  <div class="row">

    <div class="col-sm-4">
        <select id="post[category_ids][]" multiple="multiple" name="post[category_ids][]" class="form-control" size="10" required> 
          <% @categories.each do |category| %>
            <option value="<%= category.id %>"><%= category.description %></option>
          <% end %>  
        </select>
    </div>

  </div>

  <hr>

  <div class="row">
    <div class="col-sm-12">
      <%= f.simple_fields_for :tags do |builder| %> 
        <%= render 'tag_fields', f: builder %>
      <% end %>
      <%= link_to_add_association 'add item', f, :tags, :class => "btn btn-default" %>
    </div>
  </div>

  <hr>
  
  <div class="row">

    <div class="col-sm-12">
      <%= f.label :post_text %><br>
      <%= f.text_area :post_text, class: "tinymce", rows: 20 %>
      <%= tinymce %>
    </div>

  </div>


  <%= f.hidden_field :user_id, value: current_user.id %>

  <br />

  <div class="actions">
    <%= f.submit "Save post", class: "btn btn-success" %>
  </div>


<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=t(:title)%>:</strong>
  <%= @post.title %>
</p>

<p>
  <strong><%=t(:slug)%>:</strong>
  <%= @post.slug %>
</p>

<p>
  <strong><%=t(:categories)%>:</strong>
  <table>

  <% @post.categories.each do |c| %>
    <tr>
      <td>  <%= link_to c.description, c %> </td>
    </tr>
  <% end %>  
  </table>
  
</p>

<p>
  <strong>Tags:</strong>
  <table>
    <% @post.tags.each do |t| %>
      <tr>
      	<p> <%= link_to t.tag, t %> </p>
      </tr>
    <% end %>
  </table>
</p>

<p>
  <strong>Post text:</strong>
  <%= simple_format @post.post_text %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>

<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

app/views/shared/_navigation.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Challenge</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to('Home', home_path)  %>  </li>
            <% end %>
            <li><%= link_to('Categories', categories_path)  %></li>
            <li><%= link_to('Posts', posts_path)  %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>  </li>
            <% else %>
              <li><%= link_to('Login', new_user_session_path) %> </li>
            <% end %>
            <% if user_signed_in? %>
              <li><%= link_to('Edit account', edit_user_registration_path) %></li>
            <% else %>
              <li><%= link_to('Sign up', new_user_registration_path)  %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    

app/views/tags/_list_posts.html.erb
<table class="table table-bordered">
	<thead>
		<th> <%= t(:title) %> </th>
		<th> <%= t(:user) %> </th>
		<th> <%= t(:published_on) %> </th>
		<th></th>
	</thead>
	<tbody>
		<% @posts.each do |tag| %>
		<tr>
			<td> <%=tag.post.title%> </td>
			<td> <%=tag.post.user.email%> </td>
			<td> <%= l(tag.post.created_at) %></td>
			<td> <%= link_to t(:see), tag.post %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/tags/show.html.erb
<h1><%=t(:tags)%></h1>

<b> <%=t(:tag)%>: </b> <%=@tag.tag%>


<% if @posts.present? %>
	<%= render 'list_posts'%>
<% else %>
	<div class="alert alert-info">No post found</div>
<% end %>

app/views/tinymce_assets/create.html.erb
<h1>TinymceAssets#create</h1>
<p>Find me in app/views/tinymce_assets/create.html.erb</p>